AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  UserDataLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.fitmymacros.UserDataLambda::handleRequest
      Runtime: java11
      CodeUri: target/userDataLambda-jar-with-dependencies.jar
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: 
                - "arn:aws:dynamodb:eu-west-3:829527069263:table/FitMyMacros"
      MemorySize: 512
      Timeout: 30
      
  UserDataLambdaAlias:
     Type: AWS::Lambda::Alias
     DependsOn: UserDataLambdaFunction
     Properties:
      FunctionName: !Ref UserDataLambdaFunction
      FunctionVersion: $LATEST
      Name: dev  