version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven using Docker"
  pre_build:
    commands:
      - cd userdataLambda
      - echo "Executing pre-build commands"
  build:
    commands:
      - echo "Compiling the Maven project"
      - docker run --rm -v $(pwd):/usr/src/mymaven -w /usr/src/mymaven maven:3.8.4 mvn clean compile assembly:single -DskipTests=false
      - sam deploy --template-file template.yaml --stack-name userdatalambda-stack --capabilities CAPABILITY_IAM --s3-bucket fit-my-macros
